architecture: FasterRCNN
train_feed: FasterRCNNTrainFeed
eval_feed: FasterRCNNEvalFeed
test_feed: FasterRCNNTestFeed
use_gpu: true
max_iters: 180000
log_smooth_window: 20
save_dir: output
snapshot_iter: 10000
pretrain_weights: ~
metric: COCO
weights: output/thundernet_1x/model_final
num_classes: 81

FasterRCNN:
  backbone: SNet49
  rpn_head: ThunderNetRPNHead
  roi_extractor: ThunderNetRoIAlign
  bbox_head: BBoxHead
  bbox_assigner: BBoxAssigner

SNet49:
  norm_decay: 0.0
  conv_learning_rate: 1.0

ThunderNetRPNHead:
  anchor_generator:
#    anchor_sizes: [12.8, 25.6, 51.2, 102.4, 204.8]
    anchor_sizes: [32, 64, 128, 256, 512]
    aspect_ratios: [0.5, 1.0, 2.0]
    stride: [16.0, 16.0]
    variance: [1.0, 1.0, 1.0, 1.0]
  rpn_target_assign:
    rpn_batch_size_per_im: 256
    rpn_fg_fraction: 0.5
    rpn_negative_overlap: 0.3
    rpn_positive_overlap: 0.7
    rpn_straddle_thresh: 0.0
    use_random: true
  train_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    pre_nms_top_n: 12000
    post_nms_top_n: 2000
  test_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    pre_nms_top_n: 6000
    post_nms_top_n: 1000

ThunderNetRoIAlign:
  resolution: 7
  sampling_ratio: 2
  spatial_scale: 0.0625

BBoxAssigner:
  batch_size_per_im: 512
  bbox_reg_weights: [0.1, 0.1, 0.2, 0.2]
  bg_thresh_hi: 0.5
  bg_thresh_lo: 0.0
  fg_fraction: 0.25
  fg_thresh: 0.5

BBoxHead:
  head: OneFCHead
  nms:
    keep_top_k: 100
    nms_threshold: 0.5
    score_threshold: 0.05

LearningRate:
  base_lr: 0.01
  schedulers:
    - !PiecewiseDecay
      gamma: 0.1
      milestones: [120000, 160000]
    - !LinearWarmup
      start_factor: 0.3333333333333333
      steps: 500

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0001
    type: L2

FasterRCNNTrainFeed:
  # batch size per device
  batch_size: 1
  dataset:
    dataset_dir: D:\Datasets\coco
    annotation: annotations/instances_train2017.json
    image_dir: train2017
  drop_last: false
  num_workers: 2
  sample_transforms:
    - !DecodeImage
        to_rgb: true
    - !NormalizeImage
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
        is_scale: true
        is_channel_first: false
    - !ResizeImage
        target_size: 320
        max_size: 533
        interp: 1
    - !Permute
        to_bgr: false
  batch_transforms:
    - !PadBatch
        pad_to_stride: 32


FasterRCNNEvalFeed:
  batch_size: 128
  dataset:
    dataset_dir: D:\Datasets\coco
    annotation: annotations/instances_val2017.json
    image_dir: val2017
  num_workers: 4
  sample_transforms:
    - !DecodeImage
        to_rgb: true
    - !NormalizeImage
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
        is_scale: true
        is_channel_first: false
    - !ResizeImage
        target_size: 320
        max_size: 533
        interp: 1
    - !Permute
        to_bgr: false
  batch_transforms:
    - !PadBatch
        pad_to_stride: 32

FasterRCNNTestFeed:
  batch_size: 1
  dataset:
    annotation: D:\Datasets\coco/annotations/instances_val2017.json
